### ISSUE TITLE
Enabling plugin crashes discord

### ISSUE THREAD

**Issue by Ant1-dev** [sarahkittyy/KeywordTracker#99]
![Image](https://github.com/user-attachments/assets/7e28868a-f40b-415e-8d87-c95bf1e37cbf)
```
Error: Minified React error #284; visit https://react.dev/errors/284 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at aa (https://discord.com/assets/web.bca75a43edb4c883.js:12:1150275)
    at aS (https://discord.com/assets/web.bca75a43edb4c883.js:12:1162665)
    at lF (https://discord.com/assets/web.bca75a43edb4c883.js:12:1202303)
    at lU (https://discord.com/assets/web.bca75a43edb4c883.js:12:1201388)
    at lj (https://discord.com/assets/web.bca75a43edb4c883.js:12:1201230)
    at lT (https://discord.com/assets/web.bca75a43edb4c883.js:12:1198315)
    at co (https://discord.com/assets/web.bca75a43edb4c883.js:12:1208004)
    at ct (https://discord.com/assets/web.bca75a43edb4c883.js:12:1206790)
    at lR (https://discord.com/assets/web.bca75a43edb4c883.js:12:1199883)
    at Object.e [as f] (https://discord.com/assets/web.bca75a43edb4c883.js:12:1230888)
    at t.flushSync (https://discord.com/assets/web.bca75a43edb4c883.js:12:1250788)
    at j.toggleShow (https://discord.com/assets/web.bca75a43edb4c883.js:12:3091521)
    at j.hide (https://discord.com/assets/web.bca75a43edb4c883.js:12:3091339)
    at https://discord.com/assets/web.bca75a43edb4c883.js:12:3092154
    at ch (https://discord.com/assets/web.bca75a43edb4c883.js:12:1210927)
    at https://discord.com/assets/web.bca75a43edb4c883.js:12:1215976
    at tM (https://discord.com/assets/web.bca75a43edb4c883.js:12:1104309)
    at cO (https://discord.com/assets/web.bca75a43edb4c883.js:12:1212234)
    at uG (https://discord.com/assets/web.bca75a43edb4c883.js:12:1242447)
    at uj (https://discord.com/assets/web.bca75a43edb4c883.js:12:1242269)


    at div (<anonymous>)
    at ReactWrapper (betterdiscord://plugins/0PluginLibrary.plugin.js:2434:17)
    at div (<anonymous>)
    at div (<anonymous>)
    at M (https://discord.com/assets/web.bca75a43edb4c883.js:12:12662473)
    at section (<anonymous>)
    at betterdiscord/renderer.js:5:41451
    at L (https://discord.com/assets/646eb83d5f98dce6.js:1:61932)
    at u (https://discord.com/assets/web.bca75a43edb4c883.js:12:3648489)
    at k (https://discord.com/assets/646eb83d5f98dce6.js:1:63422)
    at a (https://discord.com/assets/web.bca75a43edb4c883.js:12:3076861)
    at d (https://discord.com/assets/web.bca75a43edb4c883.js:12:3078388)
    at div (<anonymous>)
    at div (<anonymous>)
    at tl (https://discord.com/assets/dad13097fe1bfae0.js:1:148148)
    at div (<anonymous>)
    at https://discord.com/assets/web.bca75a43edb4c883.js:12:2708606
    at https://discord.com/assets/dad13097fe1bfae0.js:1:155063
    at eL (https://discord.com/assets/322c162705a9505d.js:1:14974)
    at t (https://discord.com/assets/web.bca75a43edb4c883.js:12:1286052)
    at d (https://discord.com/assets/web.bca75a43edb4c883.js:12:3654357)
    at t (https://discord.com/assets/web.bca75a43edb4c883.js:12:1286722)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at eX (https://discord.com/assets/322c162705a9505d.js:1:21749)
    at div (<anonymous>)
    at n (https://discord.com/assets/web.bca75a43edb4c883.js:1:535940)
    at L (https://discord.com/assets/322c162705a9505d.js:1:226977)
    at div (<anonymous>)
    at _ (https://discord.com/assets/web.bca75a43edb4c883.js:12:10836084)
    at R (https://discord.com/assets/322c162705a9505d.js:1:227206)
    at D (https://discord.com/assets/322c162705a9505d.js:1:228113)
    at div (<anonymous>)
    at h (https://discord.com/assets/web.bca75a43edb4c883.js:12:3025368)
    at https://discord.com/assets/322c162705a9505d.js:1:213070
    at Authenticated(<Unknown>) (<anonymous>)
    at p (https://discord.com/assets/322c162705a9505d.js:1:145796)
    at t (https://discord.com/assets/web.bca75a43edb4c883.js:12:1286052)
    at t (https://discord.com/assets/web.bca75a43edb4c883.js:12:1286722)
    at ts (https://discord.com/assets/322c162705a9505d.js:1:49741)
    at Suspense (<anonymous>)
    at d (<anonymous>)
    at t (https://discord.com/assets/web.bca75a43edb4c883.js:12:1286052)
    at t (https://discord.com/assets/web.bca75a43edb4c883.js:12:1286722)
    at div (<anonymous>)
    at c (https://discord.com/assets/web.bca75a43edb4c883.js:12:4608254)
    at m (https://discord.com/assets/web.bca75a43edb4c883.js:12:2838209)
    at VerificationLayerProvider (<anonymous>)
    at m (https://discord.com/assets/web.bca75a43edb4c883.js:12:4611246)
    at d (https://discord.com/assets/web.bca75a43edb4c883.js:12:4609240)
    at div (<anonymous>)
    at div (<anonymous>)
    at m (https://discord.com/assets/web.bca75a43edb4c883.js:12:2838209)
    at AppLayerProvider (<anonymous>)
    at b (https://discord.com/assets/web.bca75a43edb4c883.js:12:3452247)
    at M (https://discord.com/assets/web.bca75a43edb4c883.js:12:12662473)
    at C (https://discord.com/assets/web.bca75a43edb4c883.js:12:4753831)
    at d (https://discord.com/assets/web.bca75a43edb4c883.js:12:3170659)
    at m (https://discord.com/assets/web.bca75a43edb4c883.js:12:3470713)
    at f (https://discord.com/assets/web.bca75a43edb4c883.js:12:7577036)
    at s (https://discord.com/assets/web.bca75a43edb4c883.js:12:3077774)
    at y (https://discord.com/assets/web.bca75a43edb4c883.js:12:7573313)
    at eb (https://discord.com/assets/web.bca75a43edb4c883.js:12:4745715)
    at er (https://discord.com/assets/web.bca75a43edb4c883.js:12:3120582)
    at eo (https://discord.com/assets/web.bca75a43edb4c883.js:12:3125326)
    at f (https://discord.com/assets/web.bca75a43edb4c883.js:12:10265542)
    at https://discord.com/assets/web.bca75a43edb4c883.js:12:1079710
    at m (https://discord.com/assets/web.bca75a43edb4c883.js:12:1074166)
    at f (https://discord.com/assets/web.bca75a43edb4c883.js:12:2793879)
    at App (<anonymous>)
    at t (https://discord.com/assets/web.bca75a43edb4c883.js:12:1283389)
    at t (https://discord.com/assets/web.bca75a43edb4c883.js:12:1262189)
    at c (https://discord.com/assets/web.bca75a43edb4c883.js:12:7290955)
    at f (https://discord.com/assets/web.bca75a43edb4c883.js:12:7577036)
    at s (https://discord.com/assets/web.bca75a43edb4c883.js:12:3077774)
    at y (https://discord.com/assets/web.bca75a43edb4c883.js:12:7573313)
```

**Comment by razerk1** [comment]
same error

**Comment by SaiyanOfDarkness** [comment]
I can also confirm, once I disabled the plugin, discord would load.  The only way I was able to find out this information was opening dev tools and clicking console tab and hit the reload button.

**Comment by OshidaBCF** [comment]
it appears that zerebos' "BDPluginLibrary" (or 0PluginLibrary.plugin.js) finally broke with possible new discord update

sadly the lib is used by multiple plugins and while this one might get updated soon, the rest probably won't, which is a real shame

**Comment by Tenome** [comment]
Hope this one gets updated, it's the reason I installed BD in the first place.

**Comment by rotorot0** [comment]
I just checked this again and it loads now without crashing, seems whatever was causing the issue was fixed by the BD devs

**Comment by Tenome** [comment]
Still broken for me after running a repair installation, and there's been no update to the BD Github. I guess you just got lucky.

**Comment by rotorot0** [comment]
Strange. It's all fine for me here. Using all of these with no issues, except MLV2 which its menu does not open.
Using BD 1.12.4

![Image](https://github.com/user-attachments/assets/28f640f3-8a91-4992-a815-255745f28a3a)

![Image](https://github.com/user-attachments/assets/964c3583-7f0e-40aa-a613-f3653de42170)

**Comment by OshidaBCF** [comment]
It's likely that you didn't received the discord update that broke the lib

because discords update are in "waves" sometime stuff break for only some peoples

**Comment by rotorot0** [comment]
I did as a matter of fact. Just yesterday it was broken both on windows and linux on my end.
Here's my client version

![Image](https://github.com/user-attachments/assets/702f6f50-0874-494d-9726-5f01a1e20062)

-- Edit --

Okay, I just figured out what I did. I somehow managed to run into a fixed Zeres Lib and installed it. I have no idea how I managed this, just that it works.

https://gist.github.com/rotorot0/113034ce6eec87755efca1258106fe7d

Functioning normally on windows too

![Image](https://github.com/user-attachments/assets/572f2423-5d71-4978-97e7-17e7b92eb1bc)

**Comment by Tenome** [comment]
Nice, that seems to have fixed it. Thanks!

**Comment by holypalaswe** [comment]
> I did as a matter of fact. Just yesterday it was broken both on windows and linux on my end. Here's my client version
> 
> ![Image](https://github.com/user-attachments/assets/702f6f50-0874-494d-9726-5f01a1e20062)
> 
> -- Edit --
> 
> Okay, I just figured out what I did. I somehow managed to run into a fixed Zeres Lib and installed it. I have no idea how I managed this, just that it works.
> 
> https://gist.github.com/rotorot0/113034ce6eec87755efca1258106fe7d
> 
> Functioning normally on windows too
> 
> ![Image](https://github.com/user-attachments/assets/572f2423-5d71-4978-97e7-17e7b92eb1bc)

Been using this for a while and has been working perfectly.
But a few days ago the color of the text changed and is now hard to read:

<img width="443" height="168" alt="Image" src="https://github.com/user-attachments/assets/0d4e7ce9-5400-4287-800c-ff9dc773b9ef" />

if I change discord appearance to white, the text turns white as well.

**Comment by razorloves** [comment]
> Been using this for a while and has been working perfectly. But a few days ago the color of the text changed and is now hard to read:
> if I change discord appearance to white, the text turns white as well.

easy fix:  open the KeywordTracker.plugin.js file in a text editor and change all 3 instances of `text-normal` to `text-default`
